baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.capturelabs.ai" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lawinslow

permalink: :title
title: Luke Winslow Blog

# Build settings
plugins:
  - jekyll-seo-tag

markdown: kramdown

# Default front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: /assets/images/feature.webp
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
