baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.capturelabs.ai" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lawinslow

permalink: :title
title: Luke Winslow Blog

# Build settings
plugins:
  - jekyll-seo-tag

markdown: kramdown
redcarpet:
  extensions: ["footnotes"]


# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
